# Generated by Django 5.0.7 on 2024-07-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('truck_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlasticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.PositiveIntegerField(default=0)),
                ('hdpe', models.PositiveIntegerField(default=0)),
                ('pvc', models.PositiveIntegerField(default=0)),
                ('other', models.PositiveIntegerField(default=0)),
                ('organic', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
    ]
