# Generated by Django 5.0.7 on 2024-07-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('organization_name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('waste_type', models.CharField(choices=[('PET', 'PET'), ('HDPE', 'HDPE'), ('PVC', 'PVC'), ('Organic', 'Organic'), ('Others', 'Others')], max_length=50, verbose_name='Type of Waste Needed')),
                ('amount_needed', models.PositiveIntegerField(verbose_name='Amount of Waste Needed (kg)')),
            ],
        ),
    ]
