# Generated by Django 5.0.3 on 2024-07-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productshop',
        ),
    ]
