# Generated by Django 5.0.7 on 2024-07-25 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_wasterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Request Date'),
            preserve_default=False,
        ),
    ]
