# Generated by Django 4.2.2 on 2024-03-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_productshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshop',
            name='image',
            field=models.ImageField(upload_to='productshop_images/'),
        ),
    ]
