# Generated by Django 5.0.7 on 2024-07-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_wasterequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasterequest',
            name='request_date',
            field=models.DateField(auto_now_add=True, verbose_name='Request Date'),
        ),
    ]
