# Generated by Django 5.0.7 on 2024-07-26 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_product_contact_details_product_organisation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='contact_details',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
